# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [112]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [113]:
print(np.__version__)

2.1.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [114]:
a = np.random.random((2, 3, 5))
print(a)

[[[0.41931453 0.69456946 0.71415966 0.27016559 0.99873823]
  [0.53621668 0.24164227 0.50151511 0.94648152 0.0264317 ]
  [0.32641483 0.02030942 0.59742639 0.63121064 0.57133987]]

 [[0.56692273 0.78400546 0.73071587 0.059061   0.4378129 ]
  [0.91864891 0.27678189 0.80921178 0.51650825 0.4388039 ]
  [0.69187528 0.69361283 0.09839499 0.35555527 0.03608693]]]


In [115]:
a = np.random.rand(2, 3, 5)
print(a)

[[[6.83702539e-01 1.01254737e-01 4.20779903e-01 9.92002382e-01
   2.99985449e-02]
  [8.97737518e-01 5.60554311e-02 3.40334817e-01 6.29364046e-01
   5.90347585e-01]
  [6.04156658e-01 1.86181252e-01 4.45367573e-01 8.30747462e-01
   1.18223801e-01]]

 [[2.71851307e-02 6.67759547e-01 8.43708348e-01 3.45551426e-01
   1.12663959e-04]
  [9.57598391e-01 7.83861109e-01 4.34906251e-01 7.20152553e-01
   8.17165126e-01]
  [8.39329409e-01 5.25392449e-01 2.36199091e-01 7.01767450e-01
   3.43099566e-01]]]


In [116]:
a = np.random.randint(100, size=(2, 3, 5))
print(a)

[[[73 82 84 69 79]
  [91 48 27 42 74]
  [64 61  9 32 49]]

 [[ 5 33 65 38 42]
  [ 4 48 87 55 64]
  [ 4 16 36 19 57]]]



### 4. Print a.


In [117]:
print(a)

[[[73 82 84 69 79]
  [91 48 27 42 74]
  [64 61  9 32 49]]

 [[ 5 33 65 38 42]
  [ 4 48 87 55 64]
  [ 4 16 36 19 57]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [118]:
b = np.ones((5, 2, 3), dtype=int)



### 6. Print b.


In [119]:
print(b)


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [120]:
print(f"The size of a is {a.size}")
print(f"The size of b is {b.size}")
a.size == b.size


The size of a is 30
The size of b is 30


True


### 8. Are you able to add a and b? Why or why not?


In [121]:
c = a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
# We are not able to add a and b because the shape is different
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
c = np.transpose(b, axes=[1, 2, 0])
c.shape
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
print(a)
print(b)
print(d)
# It works because they have the same shape

[[[68 45 97  2 58]
  [47 40 48 38 17]
  [52 47 89 46 94]]

 [[15 51 57 62 81]
  [ 1  9 54  3 61]
  [38 51 48 99 57]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[ 69  46  98   3  59]
  [ 48  41  49  39  18]
  [ 53  48  90  47  95]]

 [[ 16  52  58  63  82]
  [  2  10  55   4  62]
  [ 39  52  49 100  58]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print(d)
# the array d is similar than a but it has summed +1 to each element of a
# d - a == np.ones(a.shape)

[[[68 45 97  2 58]
  [47 40 48 38 17]
  [52 47 89 46 94]]

 [[15 51 57 62 81]
  [ 1  9 54  3 61]
  [38 51 48 99 57]]]
[[[ 69  46  98   3  59]
  [ 48  41  49  39  18]
  [ 53  48  90  47  95]]

 [[ 16  52  58  63  82]
  [  2  10  55   4  62]
  [ 39  52  49 100  58]]]



### 12. Multiply a and c. Assign the result to e.


In [ ]:
e = a * c
print(e)


[[[68 45 97  2 58]
  [47 40 48 38 17]
  [52 47 89 46 94]]

 [[15 51 57 62 81]
  [ 1  9 54  3 61]
  [38 51 48 99 57]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
print(e)
print(a)
print(c)
e == a

# Because c is an array conformed by 1s


[[[68 45 97  2 58]
  [47 40 48 38 17]
  [52 47 89 46 94]]

 [[15 51 57 62 81]
  [ 1  9 54  3 61]
  [38 51 48 99 57]]]
[[[68 45 97  2 58]
  [47 40 48 38 17]
  [52 47 89 46 94]]

 [[15 51 57 62 81]
  [ 1  9 54  3 61]
  [38 51 48 99 57]]]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"The maximum, minimum and mean of d are {d_max}, {d_min}, {d_mean:.2f}")

The maximum, minimum and mean of d are 100, 2, 50.17



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [ ]:
f = np.empty((2, 3, 5), dtype=int)
f


array([[[                 68, 4627730092099895296,                  97,
         4627730092099895296,                  58],
        [4627730092099895296, 4627730092099895296, 4627730092099895296,
         4627730092099895296, 4627730092099895296],
        [                 52, 4627730092099895296,                  89,
         4627730092099895296,                  94]],

       [[4627730092099895296,                  51,                  57,
                          62,                  81],
        [                  1, 4627730092099895296,                  54,
         4627730092099895296,                  61],
        [4627730092099895296,                  51, 4627730092099895296,
                          99,                  57]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
f[(d>d_min)&(d<d_mean)] = 25
f[(d>d_mean)&(d<d_max)] = 75
f[(d==d_mean)] = 50
f[d==d_min] = 0
f[d==d_max] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
print(d)
print(f)

[[[ 69  46  98   3  59]
  [ 48  41  49  39  18]
  [ 53  48  90  47  95]]

 [[ 16  52  58  63  82]
  [  2  10  55   4  62]
  [ 39  52  49 100  58]]]
[[[ 75  25  75  25  75]
  [ 25  25  25  25  25]
  [ 75  25  75  25  75]]

 [[ 25  75  75  75  75]
  [  0  25  75  25  75]
  [ 25  75  25 100  75]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
g = np.empty((2, 3, 5), dtype=str)
g[(d>d_min)&(d<d_mean)] = "A"
g[(d>d_mean)&(d<d_max)] = "B"
g[(d==d_mean)] = "C"
g[d==d_min] = "D"
g[d==d_max] = "E"
print(g)

[[['B' 'A' 'B' 'A' 'B']
  ['A' 'A' 'A' 'A' 'A']
  ['B' 'A' 'B' 'A' 'B']]

 [['A' 'B' 'B' 'B' 'B']
  ['D' 'A' 'B' 'A' 'B']
  ['A' 'B' 'A' 'E' 'B']]]
